@startuml

actor Jugador
actor Interfaz
actor SistemaDeJuego
actor GestorOpciones

rectangle "Sistema del Videojuego" {
  usecase "login"
  usecase "iniciarJuego"
  usecase "finalizarJuego"
  usecase "disparar"
  usecase "usarHabilidad"
  usecase "desplazarse"
  usecase "morir"
  usecase "habilidadEspecial"
}

Jugador --> "usarHabilidad"
Jugador --> "desplazarse"
Jugador --> "habilidadEspecial"
Jugador --> "morir"

Interfaz --> "login"
Interfaz --> "iniciarJuego"
Interfaz --> "finalizarJuego"

SistemaDeJuego --> "morir"
SistemaDeJuego --> "iniciarJuego"
SistemaDeJuego --> "finalizarJuego"

GestorOpciones --> "disparar"
Jugador --> GestorOpciones

@enduml