@startuml
actor Usuario
participant "videojuego" as Videojuego
participant "jugador" as Jugador
participant "enemigo" as Enemigo

Usuario -> Videojuego : login(id_usuario, password)
Videojuego -> Usuario : mostrarPantallaInicio()

Usuario -> Videojuego : iniciarjuego()
Videojuego -> Jugador : crearInstanciaJugador()
Jugador -> Videojuego : confirmarInicio()

Jugador -> Enemigo : disparar()
Enemigo -> Jugador : disparar()
Jugador -> Enemigo : contabilizardanio()
Enemigo -> Enemigo : esquivar()
Enemigo -> Enemigo : usarhabilidad()
Jugador -> Jugador : morir()
Enemigo -> Enemigo : morir()

Usuario -> Jugador : habilidadespecial()
Jugador -> Enemigo : atacar()

Usuario -> Videojuego : finalizarjuego()
Videojuego -> Jugador : finalizarjuego()
Videojuego -> Usuario : mostrarResumen()

@enduml