@startuml
class interfaz{
    +id_usuario
    #password
    
    +login()
    +iniciarjuego()
    +finalizarjuego()
}
class Personaje{
    -nombre
    -puntos_de_salud
    -habilidad

    +atacar()
    +usarhabilidad()
    +morir()
    +desplazarse()
    
}
class jugador{
    -nombre 
    -puntos_de_salud
    -habilidad
    
    +disparar() 
    +finalizarjuego()
    +habilidadespecial()
    +morir()
}

class enemigo{
    -nombre
    -puntos_de _salud
    -habilidad
    -tipo

    +morir()
    +esquivar()
    +usarhabilidad()
    
}


Personaje <|-- jugador
Personaje <|-- enemigo


@enduml
